config/routes.rb
RecordCollector::Application.routes.draw do
  get "music/index"

  root 'music#index'

  resources :albums

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def new
  end

  def create
    render text: params[:album].inspect
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/music_helper.rb
module MusicHelper
end

app/views/albums/new.html.erb
<h1 id="rubyist">Rubyist</h1>

<%= form_for :album, url: albums_path  do |f| %>

<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :year, "Year" %>
  <%= f.text_field :year %>
</p>

<p>
  <%= f.submit "Submit", :disable_with => 'Submiting...' %>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecordCollector</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/music/index.html.erb
<h1>Music#index</h1>
<h2>Foo</h2>
<p>Find me in app/views/music/index.html.erb</p>